apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: helxapp-editor-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: builder
    app.kubernetes.io/part-of: builder
    app.kubernetes.io/managed-by: kustomize
  name: helxappinstance-editor-rolebinding
  namespace: jeffw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helxappinstance-editor-role
subjects:
- kind: ServiceAccount
  name: jeffw
  namespace: jeffw
